### ISSUE TITLE
Support for protocol support or viarewind?

### ISSUE THREAD

**Issue by MagnetiteMC** [thekeenant/Tabbed#14]
It would be nice to have support for protocol support or via rewind so 1.7 players can see the tablist correctly.

**Comment by thekeenant** [comment]
Unfortunately I am not updating this repo any more, but if you want to take a stab at it, go right ahead.

If I remember correctly, 1.8 kind of overhauled the tablist system and made it easier to create a plugin like Tabbed. 1.7 would be possible, but challenging.
