### ISSUE TITLE
Unable to get titled tab list to work.

### ISSUE THREAD

**Issue by KingsMMA** [thekeenant/Tabbed#20]
I used the following code on join:
`Tabbed tabbed = Main.getInst().tabbed;
        TableTabList list = tabbed.newTableTabList(event.getPlayer(), 3, 20);
        TextTabItem playersHeader = new TextTabItem("&a&lPlayers: &f(" + Bukkit.getOnlinePlayers().size() + ")", 1, Skins.getDot(ChatColor.DARK_GRAY));
        list.set(0, 0, playersHeader);
        int i = 0;
        for (Player player : Bukkit.getOnlinePlayers()) {
            if (i < 19) list.set(0, i, new PlayerTabItem(player));
            else break;
            i++;
        }
        list.setBatchEnabled(true);
        list.update();`
It results in this:
![image](https://user-images.githubusercontent.com/63374258/126891497-53e2e162-66d9-40fb-ad32-a440847106e8.png)

The columns don't have a minimum width of 20, my name appears twice, and the players text doesn't appear.
Any ideas on what I'm doing wrong?

**Comment by skyeredwood** [comment]
This plugin was built for 1.8/1.9 so it most likely isn't functioning correctly using a later version.

Out of interest, I'm presuming you found a different solution considering this issue was opened around 3 months ago - would you mind sharing what it was?
