### ISSUE TITLE
1.9 Invisible Players

### ISSUE THREAD

**Issue by thekeenant** [thekeenant/Tabbed#9]
See related discussion:
https://github.com/Xephi/AuthMeReloaded/issues/576
https://github.com/dmulloy2/ProtocolLib/issues/157

**Comment by danieltabrizian** [comment]
Hey, i came on here to report the issue, just to find out its already posted here. My real issue is that im not even running 1.9 im running 1.8.8

 INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by thekeenant** [comment]
Are you allowing 1.9 players via any special plugin? @danieltabrizian

**Comment by danieltabrizian** [comment]
Nope, do you know any version you have tested that this issue isnt present on?

**Comment by danieltabrizian** [comment]
How can i make players appear visible?

**Comment by thekeenant** [comment]
There is no fix right now. Minecraft changed the way players are spawned making it difficult for tablist plugins like this.

I might get to working on it today. @danieltabrizian

**Comment by thekeenant** [comment]
I've got a solution in the works!

**Comment by danieltabrizian** [comment]
I worked on this too today,
I noticed if i disable the tablist on playerjoin and then reset it a second after the player is joined the tablist will showup correctly without the players being hidden. But when the players despawn on their screens it wont spawn again when they get closer and i cant figure out how to use the packet: "PacketPlayOutNamedEntitySpawn" which gets callled when it tries to spawn the entity again.
Btw, are you saying the fix will be for 1.9 because im on 1.8.3 and so are my test clients

**Comment by thekeenant** [comment]
I am focusing on 1.9 currently, but maybe this would fix the same issue in 1.8.

I think it would work to listen to the spawn packets, cancel them, send a player info packet, and resend the spawn packet after a small delay.

**Comment by danieltabrizian** [comment]
I tried to do that but i am not too familiar with packets so i didnt really knew how to. Can you guide me to the right direction please?

**Comment by danieltabrizian** [comment]
I know how to listen for the spawn packet
Just how to i create both of the other packets?

**Comment by thekeenant** [comment]
I am adding it into Tabbed itself!

**Comment by danieltabrizian** [comment]
Really? By when can i have it?

**Comment by thekeenant** [comment]
Depends on if this works, I don't know really :S

**Comment by thekeenant** [comment]
@danieltabrizian Try the latest build? Name tags might be breaking though.

**Comment by thekeenant** [comment]
The latest works, doesn't break name tags, but only works with a full tab list (table tablist 4x20)

**Comment by danieltabrizian** [comment]
Awesome!

**Comment by danieltabrizian** [comment]
Where can i get the compiled jar?

**Comment by thekeenant** [comment]
https://ci.avicus.net/view/Third%20Party/job/Tabbed/lastSuccessfulBuild/artifact/target/tabbed-1.7-SNAPSHOT.jar

(https://ci.avicus.net/view/Third%20Party/job/Tabbed/)

**Comment by thekeenant** [comment]
Moving to a separate issue #10 now.

**Comment by danieltabrizian** [comment]
When initiating "PlayerTabItem" it will throw a nullpointer:

`Caused by: java.lang.NullPointerException
        at com.keenant.tabbed.tablist.SimpleTabList.getUpdate(SimpleTabList.java:251) ~[?:?]
        at com.keenant.tabbed.tablist.SimpleTabList.getUpdate(SimpleTabList.java:280) ~[?:?]
        at com.keenant.tabbed.tablist.SimpleTabList.update(SimpleTabList.java:242) ~[?:?]
        at com.keenant.tabbed.tablist.SimpleTabList.update(SimpleTabList.java:209) ~[?:?]
        at com.keenant.tabbed.tablist.SimpleTabList.set(SimpleTabList.java:147) ~[?:?]
        at com.keenant.tabbed.tablist.SimpleTabList.set(SimpleTabList.java:138) ~[?:?]
        at com.keenant.tabbed.tablist.TableTabList.set(TableTabList.java:124) ~[?:?]
        at solutions.elitedev.potionpvp.Tab.TabManager.createTab(TabManager.java:157) ~[?:?]
        at solutions.elitedev.potionpvp.Tab.TabManager.onJoin(TabManager.java:59) ~[?:?]`

**Comment by thekeenant** [comment]
Can I see your code, that would only happen when a null skin is supplied.

**Comment by danieltabrizian** [comment]
`
PlayerProvider<String> ppv = new PlayerProvider<String>() {
            @Override
            public String get(Player player) {
                return ChatColor.DARK_AQUA+player.getName();
            }  
        };
        for(int i = 0;i < tab.getRows() && i != players.size();i++){
            Player pget= players.get(i);
            try{
                tab.set(2, i+1, new PlayerTabItem(pget, ppv));
            }catch(Exception e){  
            }
        }

`

**Comment by thekeenant** [comment]
Try the latest: https://ci.avicus.net/view/Third%20Party/job/Tabbed/6/artifact/target/tabbed-1.7-SNAPSHOT.jar

If it doesn't work, send me some more of your code, wherever you do tab things. https://pastebin.com

**Comment by danieltabrizian** [comment]
When is that latest version posted?

**Comment by thekeenant** [comment]
About 10 minutes ago.
